name: Eupry Required CI

on:
  pull_request:
  merge_group:

permissions:
  checks: read
  contents: read
  statuses: read

jobs:
  required:
    name: CI / Required
    uses: eupry/actions/.github/workflows/required-ci.yml@main
    with:
      required_checks: |
      allow_bootstrap_only: true
